[package]
name = "uniarts-cli"
version = "1.0.0"
authors = ["terry.tu <tuminfei1981@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
structopt = "0.3.8"
log = { version = "0.4.11" }

# uniarts
uniarts-service = { path = "../service", default-features = false, optional = true }
uniarts-primitives = { path = "../../primitives" }

# substratem
sp-core = { version = "2.0.1", optional = true }
sc-cli = { version = "0.8.0", optional = true }
sc-service = { version = "0.8.0", optional = true }
sc-executor = { version = "0.8.0", features = ["wasmtime"] }
frame-benchmarking-cli = { version = "2.0.1", optional = true }
sp-trie = { version = "2.0.1", default-features = false }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.1", default-features = false }

[features]
default = ["wasmtime", "cli"]
trie-memory-tracker = ["sp-trie/memory-tracker"]

wasmtime = [
    "sc-cli/wasmtime",
    "trie-memory-tracker",
]

cli = [
    "uniarts-service",
    "sp-core",
    "sc-cli",
    "sc-service",
    "frame-benchmarking-cli",
]
runtime-benchmarks = [ "uniarts-service/runtime-benchmarks" ]
