<template>
    <div class="index">
        <div class="banner-top">
            <Top />
        </div>
        <div class="guide container">
            <h2 class="title">How To use the product?</h2>
            <div class="guide-body">
                <div class="guide-item">
                    <div class="icon-bg"></div>
                    <h4>Digital wallet</h4>
                    <p>
                        Before applying for a certificate, the users needs to
                        create a digital wallet where the points generated by
                        the transaction will be saved
                    </p>
                </div>
                <router-link class="guide-item certificate" to="/certificate">
                    <div class="icon-bg"></div>
                    <h4>APPLY FOR certificates</h4>
                    <p>
                        Newly uploaded works need to apply for a certificate
                        before they can be traded.Works that already have
                        certificates can also apply for enterprise endorsement.
                    </p>
                </router-link>
                <div class="guide-item">
                    <div class="icon-bg"></div>
                    <h4>certificate querying</h4>
                    <p>
                        Users can query the information of the work according to
                        the certificate address to fully understand the work
                    </p>
                </div>
            </div>
        </div>
        <div class="guide container">
            <h2 class="title" style="text-transform: none; margin-bottom: 97px">
                Time limited auction
            </h2>
            <div class="guide-body">
                <Carousel />
            </div>
        </div>
        <div class="worklist container">
            <h2 class="title">Popular original works</h2>
            <div class="worklist-body">
                <Thumbnail :list="workList"></Thumbnail>
            </div>
        </div>
        <div class="recommendation container">
            <h2 class="title">Topic recommendation</h2>
            <div
                class="recommendation-body"
                v-for="(v, i) in recommendList"
                :key="i"
            >
                <div class="postmoder">
                    <div class="name-text">{{ v.title }}</div>
                    <div
                        class="bg"
                        :style="`background-image: url(${v.img_file.url});`"
                    ></div>
                </div>
                <Thumbnail :list="v.arts"></Thumbnail>
                <button class="more-button" @click="$router.push('/market')">
                    more works
                </button>
            </div>
        </div>
        <div class="authors container">
            <h2 class="title">Popular authors</h2>
            <div class="authors-body">
                <ArtistGroupList :list="authorList"></ArtistGroupList>
                <button class="more-button" @click="$router.push('/artist')">
                    more authors
                </button>
            </div>
        </div>
    </div>
</template>

<script>
import Carousel from "./Carousel";
import Top from "./Top";
import Thumbnail from "@/components/Thumbnail";
import ArtistGroupList from "@/components/ArtistGroupList";
export default {
    name: "index",
    components: { Carousel, Thumbnail, ArtistGroupList, Top },
    data() {
        return {
            workList: [],
            recommendList: [],
            authorList: [],
        };
    },
    created() {
        this.requestAuthorData();
        this.requestWorkData();
        this.requestRecommendData();
    },
    mounted() {},
    methods: {
        requestAuthorData() {
            this.$http
                .globalGetPopularAuthor({})
                .then((res) => {
                    this.authorList = res;
                })
                .catch((err) => {
                    console.log(err);
                    this.$notify.error(err.head ? err.head.msg : err);
                });
        },
        requestWorkData() {
            this.$http
                .globalGetPopArts({})
                .then((res) => {
                    this.workList = res;
                })
                .catch((err) => {
                    console.log(err);
                    this.$notify.error(err.head ? err.head.msg : err);
                });
        },
        requestRecommendData() {
            this.$http
                .globalGetTopicArts({})
                .then((res) => {
                    this.recommendList = res;
                })
                .catch((err) => {
                    console.log(err);
                    this.$notify.error(err.head ? err.head.msg : err);
                });
        },
    },
};
</script>

<style lang="scss" scoped>
.banner-top {
    background: white;
    height: 760px;
    margin-bottom: 105px;
    .container {
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        h1 {
            width: 100%;
            font-size: 60px;
            font-family: "Broadway";
            font-weight: 400;
            text-align: left;
            line-height: 60px;
            color: #020202;
            letter-spacing: 1px;
            margin-bottom: 50px;
        }
        .tip {
            color: #c61e1e;
            font-size: 60px;
            font-weight: 400;
            font-family: "Broadway";
            letter-spacing: 1px;
        }
    }
    .input-box {
        width: 100%;
        overflow: hidden;
        padding-right: 18%;
        .input {
            float: right;
            position: relative;
            width: 250px;
            margin-top: 10px;
            input {
                width: 100%;
                height: 48px;
                background-color: black;
                border-radius: 10px;
                color: #b5b5b5;
                padding-left: 14px;
                padding-right: 39px;
                font-size: 16px;
                text-transform: uppercase;
            }
            img {
                position: absolute;
                width: 19px;
                right: 14px;
                top: 14px;
                cursor: pointer;
            }
        }
    }
}

.carousel {
}

.guide,
.worklist,
.recommendation,
.authors {
    padding-bottom: 130px;
    .title {
        font-family: "Broadway";
        font-size: 38px;
        font-weight: 400;
        text-align: left;
        color: #020202;
        letter-spacing: 2px;
        text-transform: uppercase;
        margin-bottom: 113px;
    }
    .more-button {
        padding: 17px 96px;
        color: black;
        font-size: 25px;
        font-weight: 600;
        background: transparent;
        border: 3px solid black;
        text-transform: uppercase;
        margin-top: 93px;
        cursor: pointer;
    }
}

.guide {
    .guide-body {
        display: flex;
        align-items: flex-start;
        justify-content: space-between;
        .guide-item {
            display: flex;
            flex-direction: column;
            align-items: center;
            h4 {
                text-transform: uppercase;
                padding-top: 56px;
                font-size: 21px;
                font-weight: 600;
                text-align: center;
                letter-spacing: 0px;
            }
            p {
                max-width: 350px;
                padding-top: 27px;
                font-size: 16px;
                font-weight: 400;
                text-align: left;
                line-height: 30px;
                letter-spacing: 0px;
            }
        }
        .guide-item.certificate:hover {
            cursor: pointer;
            > h4,
            > p {
                text-decoration: underline;
            }
        }
        .guide-item:nth-child(1) .icon-bg {
            width: 105px;
            height: 66px;
            background: url("~@/assets/images/wallet@2x.png");
            background-size: 105px 66px;
            background-repeat: no-repeat;
        }
        .guide-item:nth-child(2) .icon-bg {
            width: 87px;
            height: 66px;
            background: url("~@/assets/images/cer@2x.png");
            background-size: 87px 66px;
            background-repeat: no-repeat;
        }
        .guide-item:nth-child(3) .icon-bg {
            width: 71px;
            height: 76px;
            background: url("~@/assets/images/cer-querying@2x.png");
            background-size: 71px 76px;
            background-repeat: no-repeat;
        }
        .guide-item:nth-child(3) h4,
        .guide-item:nth-child(3) p {
            transform: translateY(-10px);
        }
    }
}

.recommendation {
    .title {
        margin-bottom: 0;
    }
    .recommendation-body {
        margin-top: 150px;
    }
    .postmoder {
        margin-bottom: 57px;
        position: relative;
        .name-text {
            position: absolute;
            top: 130px;
            transform: translateY(-50%);
            padding-left: 50px;
            text-transform: uppercase;
            font-weight: 600;
            font-size: 43px;
            color: white;
        }
        .bg {
            width: 100%;
            height: 250px;
            background-image: url(~@/assets/images/topic@3x.png);
            background-repeat: no-repeat;
            background-position: center;
            background-size: 100% auto;
        }
        .post-text {
            transform: translateX(580px) translateY(-50%);
            width: 650px;
            height: 60px;
            background: url(~@/assets/images/postmodernism@3x.png) no-repeat;
            background-size: 100% auto;
        }
    }
}
</style>
